include $(APPDIR)/Make.defs

MAINSRC   = wifi_auto.c
PROGNAME  = wifi_auto
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_EXAMPLES_WIFI_AUTO)

include $(APPDIR)/Application.mk
